import type { TechStack } from "@/types/tech-stack";

export const TECH_STACK: TechStack[] = [
  {
    key: "typescript",
    title: "TypeScript",
    href: "https://www.typescriptlang.org/",
    categories: ["Language"],
  },
  {
    key: "c",
    title: "C",
    href: "https://en.wikipedia.org/wiki/C_(programming_language)",
    categories: ["Language"],
  },
  {
    key: "js",
    title: "JavaScript",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    categories: ["Language"],
  },
  {
    key: "python",
    title: "Python",
    href: "https://www.python.org/",
    categories: ["Language"],
  },
  {
    key: "PHP",
    title: "PHP",
    href: "https://www.php.net/",
    categories: ["Language"],
  },
  {
    key: "java",
    title: "Java",
    href: "https://www.java.com/",
    categories: ["Language"],
  },
  {
    key: "nodejs",
    title: "Node.js",
    href: "https://nodejs.org/",
    categories: ["Runtime Environment"],
  },
  {
    key: "Bun",
    title: "Bun",
    href: "https://bun.sh/",
    categories: ["Runtime Environment"],
  },
  {
    key: "react",
    title: "React",
    href: "https://react.dev/",
    categories: ["Library", "UI Library"],
  },
  {
    key: "nextjs2",
    title: "Next.js",
    href: "https://nextjs.org/",
    categories: ["Framework"],
    theme: true,
  },
  {
    key: "tailwindcss",
    title: "Tailwind CSS",
    href: "https://tailwindcss.com/",
    categories: ["Framework"],
  },
  {
    key: "shadcn-ui",
    title: "shadcn/ui",
    href: "https://ui.shadcn.com/",
    categories: ["Library", "Component Library"],
    theme: true,
  },
  {
    key: "Radixui",
    title: "Radix UI",
    href: "https://www.radix-ui.com/",
    categories: ["Library", "Component Library"],
    theme: true,
  },
  {
    key: "Redux",
    title: "Redux",
    href: "https://redux.js.org/",
    categories: ["State Management"],
  },
  // {
  //   key: "react-router",
  //   title: "React Router",
  //   href: "https://reactrouter.com/",
  //   categories: ["Library", "Navigation"],
  //   theme: true,
  // },
  // {
  //   key: "react-navigation",
  //   title: "React Navigation",
  //   href: "https://reactnavigation.org/",
  //   categories: ["Library", "Navigation"],
  // },
  {
    key: "Git",
    title: "Git",
    href: "https://git-scm.com/",
    categories: ["Version Control"],
  },
  {
    key: "GitHub",
    title: "GitHub",
    href: "https://github.com/",
    categories: ["Version Control"],
  },
  {
    key: "Docker",
    title: "Docker",
    href: "https://www.docker.com/",
    categories: ["Containerization"],
  },
  {
    key: "MySQL",
    title: "MySQL",
    href: "https://www.mysql.com/",
    categories: ["Database"],
  },
  {
    key: "MongoDB",
    title: "MongoDB",
    href: "https://www.mongodb.com/",
    categories: ["Database"],
  },
  // {
  //   key: "redis",
  //   title: "Redis",
  //   href: "https://redis.io/",
  //   categories: ["Database"],
  // },
  // {
  //   key: "figma",
  //   title: "Figma",
  //   href: "https://www.figma.com/",
  //   categories: ["Tools", "Design"],
  // },
  {
    key: "ps",
    title: "Adobe Photoshop",
    href: "https://www.adobe.com/vn_en/products/photoshop.html",
    categories: ["Tools", "Design"],
  },
  {
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
    theme: true,
  },
  // {
  //   key: "zalo-mini-app",
  //   title: "Zalo Mini App",
  //   href: "https://mini.zalo.me/",
  //   categories: ["Other"],
  // },
  
];
